services:
  - type: web
    name: blog-post
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: blog-data
      mountPath: /data
      sizeGB: 0.5
